# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Estado del Ticket', max_length=30, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='T\xedtulo del Ticket', max_length=100, verbose_name='titulo')),
                ('descripcion', models.CharField(help_text='Descripci\xf3n del Ticket', max_length=100, verbose_name='descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(help_text='Estado Ticket', on_delete=django.db.models.deletion.CASCADE, to='api.Estado', verbose_name='estado')),
            ],
            options={
                'permissions': (('crear_ticket', 'Puede crear tickets'),),
            },
        ),
    ]
